version: '3.7'
services:
  web:
    build: .
    command: python ctpe_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/ctpe_project
    ports:
      - 8000:8000
#    depends_on:
#      - db
#  db:
#    image: postgres:11
